### ISSUE TITLE
Can I `merge` two configurations?

### ISSUE THREAD

**Issue by fonsp** [Roger-luo/Configurations.jl#20]
It would be great if something like this could work:

```julia
options_from_toml = Configurations.from_toml(Settings, "options.toml")
options_from_kwargs = Configurations.from_kwargs(Settings, kwargs)

final_options = merge(options_from_toml, options_from_kwargs) # kwargs take precedence
```

Or is there a suggested method to achieve the same result?

**Comment by Roger-luo** [comment]
this sounds reasonable, but it's not implemented yet, I guess I forget to implement it somehow

**Comment by Roger-luo** [comment]
I'm doing a clean up of this package to split things, I'll implement this in the next version.

**Comment by Roger-luo** [comment]
I find you actually want

```julia
from_toml(Settings, "options.toml"; kwargs...)
```

after implementing `merge`, I find it's different from a mutable `Dict` here, since two options types contains each default values, so in some cases it won't make sense to overwrite the first option with the second (since what you actually want to do is to only overwrite what is specified by the keywords)
