### ISSUE TITLE
What is the current progress of JSON and YAML support?

### ISSUE THREAD

**Issue by lucifer1004** [Roger-luo/Configurations.jl#76]
I see from the codebase that you have prepared for JSON and YAML, how are things going? What is your design or plan @Roger-luo ? I would like to work on this if possible.

**Comment by Roger-luo** [comment]
Thanks for the interests! I'd like to separate JSON/YAML support to another package https://github.com/Roger-luo/KungIChi.jl which aims to provide full features of pydantic for Web API validation, etc. But I haven't got much time to work on it, and it also requires more thinking on the validation interface.

The reason we are not supporting JSON/YAML and other things in this package is also simple, these two formats and other features in pydantic require dependencies on heavier packages that would slow down the loading time of this package lot. 

Given the fact this package is used in quite a few latency-sensitive applications (Pluto and Comonicon), we won't add much new features to this package anymore. This is also why pretty printing has been moved to https://github.com/Roger-luo/GarishPrint.jl/ and we use the bootstrapped package ExproniconLite instead of [Expronicon](https://github.com/Roger-luo/Expronicon.jl/) for pattern matching enabled meta programming

**Comment by Roger-luo** [comment]
Ideally one should be able to rewrite these two packages in a simpler manner using KungIChi:

- https://github.com/QuantumBFS/IBMQClient.jl
- https://github.com/QuantumBFS/AWSBraket.jl

By directly parsing the schema definition, I believe this is something critical missing from the Julia Web community. I've implemented some support for JSON in these two packages since all the API schema is JSON-based. Also check the documentation if you need some basic JSON support intermediately: https://configurations.rogerluo.dev/stable/quick-start/#Read-JSON-files 

PS. I think future we want to support `JSON3` instead of `JSON` given the fact `JSON3` is gonna take over the previous implementations

**Comment by lucifer1004** [comment]
Thanks for sharing the information.
